---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  become: yes
  tags:
    - users

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  become: yes
  tags:
    - users

- name: Create user account
  user:
    name: "{{ item.user }}"
    shell: "/bin/bash"
    groups: 
      - users
      - wheel
    system: yes
    state: present
    append: yes
  with_items:
    - "{{ account_names }}"
  become: yes
  tags:
    - users

- name: Add ssh key for users
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
    state: present
  with_items:
    - "{{ account_names }}"
  become: yes
  tags:
    - users
